<%@ Page Title="Liste des utilisateurs" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="AdminUsers.aspx.cs" Inherits="ProjetCSharp.Data.AdminUsers" %>


<asp:Content ID="HeaderContent" runat="server" ContentPlaceHolderID="HeadContent">
</asp:Content>

<asp:Content ID="BodyContent" runat="server" ContentPlaceHolderID="MainContent">
    
    
     <h2>Utilisateurs
         <asp:Label ID="Message" ForeColor="Red" runat="server" />
         <asp:GridView 
         ID="GridView1" 
         runat="server" 
         AutoGenerateDeleteButton="false" 
         AutoGenerateColumns="False" 
         BackColor="White" BorderColor="#999999" BorderStyle="None" BorderWidth="1px" CellPadding="3" 
         DataSourceID="SqlDataSource1"  DataKeyNames="UserName,RoleName" OnRowDeleting="CustomersGridView_RowDeleting" OnRowUpdating="CustomersGridView_RowUpdating"
         GridLines="Vertical" Width="903px" OnSelectedIndexChanged="GridView1_SelectedIndexChanged1">
         <AlternatingRowStyle BackColor="#DCDCDC" />
         <Columns>
             <asp:TemplateField HeaderText="Login" >
                    <ItemTemplate>
                        <asp:Label  ID="UserName" runat="server" Text='<%#Eval("UserName") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:Label ID="UserName"  runat="server" Text='<%#Eval("UserName") %>'></asp:Label>
                    </EditItemTemplate>
                </asp:TemplateField>

             <asp:TemplateField HeaderText="Role" >
                    <ItemTemplate>
                        <asp:Label ID="RoleName" runat="server" Text='<%#Eval("RoleName") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="RoleName"  runat="server" Text='<%#Eval("RoleName") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>

             <asp:TemplateField HeaderText="Derniere Connexion" >
                    <ItemTemplate>
                        <asp:Label  ID="LastActivityDate" runat="server" Text='<%#Eval("LastActivityDate") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:Label ID="LastActivityDate"  runat="server" Text='<%#Eval("LastActivityDate") %>'></asp:Label>
                    </EditItemTemplate>
                </asp:TemplateField>

             

             

            


             

              <asp:TemplateField HeaderText="Edit">
                    <ItemTemplate>
                        <asp:Button ID="BtnEdit" runat="server" CommandName="Edit" Text="Edit" />
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:Button ID="BtnUpdate" runat="server" CommandName="Update" Text="Update" OnClick="UpdateRow_Click" />
                        
                    </EditItemTemplate>
                </asp:TemplateField>
             
             <asp:CommandField HeaderText="Supprimer" ButtonType="Image"  DeleteImageUrl="~/Images/supression.jpg" ShowDeleteButton="True"></asp:CommandField>
         
         
         </Columns>
         <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
         <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
         <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
         <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
         <SelectedRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
         <SortedAscendingCellStyle BackColor="#F1F1F1" />
         <SortedAscendingHeaderStyle BackColor="#0000A9" />
         <SortedDescendingCellStyle BackColor="#CAC9C9" />
         <SortedDescendingHeaderStyle BackColor="#000065" />
         </asp:GridView>
         <asp:SqlDataSource 
             ID="SqlDataSource1" 
             runat="server"
             ConnectionString="<%$ ConnectionStrings:ApplicationServices %>"  
             SelectCommand="
             SELECT aspnet_Users.UserName, aspnet_Roles.RoleName, aspnet_Users.LastActivityDate 
             FROM aspnet_Users,aspnet_Roles,aspnet_UsersInRoles
             WHERE aspnet_Users.UserId = aspnet_UsersInRoles.UserId
             AND aspnet_Roles.RoleId = aspnet_UsersInRoles.RoleId 
             "
             UpdateCommand="
             Update aspnet_UsersInRoles 
             Set aspnet_UsersInRoles.RoleId = 
             (Select aspnet_Roles.RoleId from aspnet_Roles where aspnet_Roles.RoleName = @RoleName)
             WHERE aspnet_UsersInRoles.UserId In (Select aspnet_Users.UserId from aspnet_Users Where aspnet_Users.UserName = @UserName) 
             "
             DeleteCommand="
             Delete From aspnet_UsersInRoles 
             where aspnet_UsersInRoles.UserId in (Select aspnet_Users.UserId from aspnet_Users  where aspnet_Users.UserName = @UserName)
             
             Delete From aspnet_Membership
             where aspnet_Membership.UserId in (Select aspnet_Users.UserId from aspnet_Users where aspnet_Users.UserName = @UserName)

             Delete From aspnet_Users where aspnet_Users.UserName = @UserName

             "
             InsertCommand=""
             >

             <DeleteParameters>
                <asp:Parameter Name="UserName" />
            </DeleteParameters>

             <UpdateParameters>
                <asp:Parameter Name="UserName" />
                 <asp:Parameter Name="RoleName" />
            </UpdateParameters>
             

         </asp:SqlDataSource>


         <asp:SqlDataSource 
             ID="SqlDataSource2" 
             runat="server"
             ConnectionString="<%$ ConnectionStrings:ApplicationServices %>"  
             SelectCommand="
             SELECT aspnet_Roles.RoleName from aspnet_Roles
             ">
         </asp:SqlDataSource>

     </h2>

      
    
</asp:Content>
